### ISSUE TITLE
Change menu highlight to red

### ISSUE THREAD

**Issue by alex-ong** [kirjavascript/TetrisGYM#10]
Hi Kirjava,

I wrote a dynamic menu-rescrambler for streaming (https://github.com/alex-ong/NESTrisAutoLayout)

Unfortunately due to how the level-select menus are blue bordered rather than red, i'm unable to tell between highscore and level select menu. Could you set level back to red? I can then adjust code on my side to make it all work.

![image](https://user-images.githubusercontent.com/6406312/134846602-329396a5-4901-4ced-adb7-d5dc20677fbd.png)
Stock and tetrisgym roms images attached.  

I only reference the pixels in the diagram below:
![image](https://user-images.githubusercontent.com/6406312/134846666-82b0ae8f-6492-4777-93ec-e690f357e415.png)
R == Grey + Green = Grey + blue == (black or undefined?) would work, with checking the orange pixel (border colour) being blue vs red for level select vs highscore.

Cheers,
Alejandro

**Comment by alex-ong** [comment]
Oh perfect response!

Yes leave it as it is I'll make a custom shader for Tetris gym. Good tip about 0x9a, I shall use that

**Comment by kirjavascript** [comment]
Good stuff, let me know if you need any more help with anything!
