### ISSUE TITLE
Confetti showing up on level loads on FPGA consoles (NESTang)

### ISSUE THREAD

**Issue by nick3252** [kirjavascript/TetrisGYM#102]
I'm using NESTang 0.10 on a Tang Nano 20k board. NESTang is based on the MIST NES core, so this issue may occur on other implementations/boards, but I don't have the hardware to test it.

Upon level loads and transitions, visual confetti is seen briefly. This issue is not visible on an emulator. Both ROMs have the same CRC `37a5ec63`.

I demonstrate this in a video, showing the main menu of the ROM as well as the current settings. I turn on dark mode to show the effect stronger, but the issue still persists with it disabled. I load in game 5 times on both NESTang and Mesen, and the effect only shows on Mesen.

https://github.com/kirjavascript/TetrisGYM/assets/90110064/5ff651e1-4d4e-4a41-afec-0306c8b74e7b

I would imagine an issue that seems to not replicate on an emulator has its roots in the NES core implementation, so if there's anything I can do to help diagnose the source of the problem, please let me know.

**Comment by kirjavascript** [comment]
hey

I think this is a bug in NESTang. The issue doesnt appear on hardware and Mesen is matching that. Other FPGA solutions like MiSTeR do not have this issue either.

I'm not sure I could fix this without digging into the internals of NESTang and debugging. If I had to guess there is some tile drawing bottleneck in the rendering that doesnt account for when NMI is disabled.

**Comment by kirjavascript** [comment]
cool, let me know if there's anything else I can do to help
