### ISSUE TITLE
Is there any way to bring back the music?

### ISSUE THREAD

**Issue by epic-64** [kirjavascript/TetrisGYM#108]
Is there some way to bring back to music to Tetris Type A games?

**Comment by kirjavascript** [comment]
I'm afraid not, the music has been removed from the ROM

**Comment by que68** [comment]
Why? I find it quite unsettling to play without the music, especially for pacing reasons. Was there a technical reason?

**Comment by kirjavascript** [comment]
it's removed to save space for other features
