### ISSUE TITLE
Feature request: Color Checker

### ISSUE THREAD

**Issue by myekul** [kirjavascript/TetrisGYM#112]
First off, I think your mod is very cool and it's awesome to see it being used across the entire NES Tetris community. Now, my feature request: with many players making it far beyond level 138 lately, I think it would be nice to implement a convenient way to check how the colors look on every level. Not exactly sure what this would look like, but I can see it being helpful for players with variable lighting setups

**Comment by kirjavascript** [comment]
you can visit each level in the level select. is that enough?

**Comment by kirjavascript** [comment]
feel free to open a new issue if you mean something else
