### ISSUE TITLE
missing .chr file 

### ISSUE THREAD

**Issue by IIpepeII** [kirjavascript/TetrisGYM#12]
Hi! 
I wanted to try your product. I'm on Win10, installed "make" through Windows Terminal(Ubuntu Shell), have a 3.8.5 python. When executing "make" in the folder got this error. What am I doing wrong? 
![makeproblem](https://user-images.githubusercontent.com/22872597/147384418-8dd4da4b-ef98-403a-8a0b-9aac740d0169.JPG)

**Comment by kirjavascript** [comment]
you just need to install python so the image decode tools work
