### ISSUE TITLE
Could you share the hashsum of the rom you're expecting?

### ISSUE THREAD

**Issue by seajaysec** [kirjavascript/TetrisGYM#2]
Hey! Awesome looking trainer. Unfortunately, I haven't been able to get it running. Would you be able to share the md5 or sha1 value of the rom that this patch is expecting?

**Comment by kirjavascript** [comment]
should be;

```File SHA-1: 77747840541BFC62A28A5957692A98C550BD6B2B
File CRC32: 6D72C53A```

do you think it merits adding to the readme?

**Comment by seajaysec** [comment]
Awesome! Just got it working. The hash definitely helped check things out beforehand. I'd totally add it to the readme!
