### ISSUE TITLE
No music option

### ISSUE THREAD

**Issue by SmashManiac** [kirjavascript/TetrisGYM#20]
Music is off by default, and there doesn't appear to be any way to select any of the original music tracks instead.

If this is due to technical limitations, this change should be documented at the very least.

Note that I wanted to play TetrisGYM on a portable system, and using an external music source while still hearing the game's SFX isn't really an option in such a situation.

**Comment by kirjavascript** [comment]
Hi!

Removal of music saves space for other features, and isn't something people have seemed to want or need so far.

Additionally, my intention is to replace the entire game, so I want to limit the copyrighted material as much as possible.

I'll add a note to the readme about it next time I do an update.
