### ISSUE TITLE
Build a v 5.1 release?

### ISSUE THREAD

**Issue by justinthiele** [kirjavascript/TetrisGYM#55]
Hi there, 

Could somebody build a new release that includes the latest updates? I tried doing it myself but when I ran `sh build.sh` I got an error that says it's `Unable to create patch on mac`. I don't have access to a non-Mac computer unfortunately.

Thank you!
Justin

**Comment by kirjavascript** [comment]
hoping to get a new version out soon!

**Comment by justinthiele** [comment]
Awesome, thank you! I'm excited for hidden score mode 👍👍

**Comment by zohassadar** [comment]
Hi @justinthiele. While the patch creation failed, compiling the rom may have succeeded.  Was a file named `tetris.nes` created?

**Comment by justinthiele** [comment]
Hey @zohassadar, I was able to successfully run the build script and get the new version running. Really appreciate the support and all the work 🎉
