### ISSUE TITLE
GARBAGE 4 warps to rocketscreen near topout 

### ISSUE THREAD

**Issue by kirjavascript** [kirjavascript/TetrisGYM#78]
https://www.youtube.com/watch?v=9qjdfWYRDtY

**Comment by kirjavascript** [comment]
[garbage4 crash.mss.tar.gz](https://github.com/kirjavascript/TetrisGYM/files/14352624/garbage4.crash.mss.tar.gz)

**Comment by kirjavascript** [comment]
[garbage4crash.mmo.tar.gz](https://github.com/kirjavascript/TetrisGYM/files/14352635/garbage4crash.mmo.tar.gz)

**Comment by kirjavascript** [comment]
block tool recreation

![tetris_000](https://github.com/kirjavascript/TetrisGYM/assets/4498266/760158cb-bce8-43ff-b407-ab9973541faf)

**Comment by zohassadar** [comment]
Captured trace log of a crash.  NMI occurred in the middle of switch_s_plus_2a due to random10 being called 270 times during the preceding frame.

**Comment by kirjavascript** [comment]
@zohassadar fixed this, I think :)
